package com.example.BookShop.entity;

import com.example.BookShop.entity.book.links.Book2AuthorEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "author")
@ApiModel(description = "data model of author entity")
public class AuthorEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @ApiModelProperty(value = "author id auto generated by db", position = 1)
    private int id;

    @ApiModelProperty(value = "photo author", position = 2)
    private String photo;

    @Column(nullable = false)
    private String slug;

    @Column(nullable = false)
    @ApiModelProperty(value = "first and last author name", example = "Jeddy Gonthard", position = 3)
    private String name;

    @Column(columnDefinition = "TEXT")
    private String description;

    @OneToMany(mappedBy = "authorId")
    @JsonIgnore
    private List<Book2AuthorEntity> authorIdList = new ArrayList<>();

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<Book2AuthorEntity> getAuthorIdList() {
        return authorIdList;
    }

    public void setAuthorIdList(List<Book2AuthorEntity> authorIdList) {
        this.authorIdList = authorIdList;
    }
}
